backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:

  # ▼ お知らせ
  - name: "news"
    label: "お知らせ"
    folder: "news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }

  # ▼ 憲法
  - name: "constitution"
    label: "憲法ページ"
    files:
      - file: "constitution.md"
        label: "憲法"
        name: "constitution"
        fields:
          - { label: "本文", name: "body", widget: "markdown" }

  # ▼ 法律（法制度）
  - name: "law"
    label: "法律ページ"
    files:
      - file: "law.md"
        label: "法律"
        name: "law"
        fields:
          - { label: "本文", name: "body", widget: "markdown" }
