backend:
  name: git-gateway
  branch: main

collections:
  - name: "test"
    label: "テスト編集"
    folder: "test"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
