backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"  # 後で変更可

collections:
  - name: "test"
    label: "テスト編集"
    folder: "test"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
