backend:
  name: github
  repo: republicofpoland/official.github.io
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "お知らせ"
    folder: "news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
